export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: 'Pan Baguette',
        description: 'Rico pan baguette',
        weight: '1/2 kg',
        price: 10,
    },
    {
        id: 2,
        category: 1,
        name: 'Pan de Queso',
        description: 'Rico Pan de queso',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 3,
        category: 2,
        name: 'Pan de Queso Integral',
        description: 'Rico Pan de queso integral',
        weight: '1/3 kg',
        price: 20,
    },
    {
        id: 4,
        category: 2,
        name: 'Pan de Yema Integral',
        description: 'Rico Pan de yema integral',
        weight: '1/3 kg',
        price: 25,
    },
    {
        id: 5,
        category: 3,
        name: 'Pan de Queso',
        description: 'Rico Pan de queso',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 6,
        category: 3,
        name: 'Pan de Queso Integral',
        description: 'Rico Pan de queso integral',
        weight: '1/3 kg',
        price: 20,
    },
    {
        id: 7,
        category: 4,
        name: 'Pan de Queso',
        description: 'Rico Pan de queso',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 8,
        category: 4,
        name: 'Pan de Queso Integral',
        description: 'Rico Pan de queso integral',
        weight: '1/3 kg',
        price: 20,
    },
]