export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: 'Golosinas',
        description: 'Golosinas super dulces',
        weight: '100 gr',
        price: 10,
    },
    {
        id: 2,
        category: 1,
        name: 'Caramelos',
        description: 'Caramelos masticables',
        weight: '200 gr',
        price: 15,
    },
    {
        id: 3,
        category: 2,
        name: 'Gomitas',
        description: 'Gomitas con azucar y sin azucar',
        weight: '300 gr',
        price: 20,
    },
    {
        id: 4,
        category: 2,
        name: 'Gomitas masticables',
        description: 'Gomas masticables de frutas',
        weight: '500 kg',
        price: 25,
    },
    {
        id: 5,
        category: 3,
        name: 'Chicle',
        description: 'chicles con sabores frutales',
        weight: '200 gr',
        price: 15,
    },
    {
        id: 6,
        category: 3,
        name: 'Chicles',
        description: 'chicles con sabor a menta',
        weight: '200 gr',
        price: 20,
    },
    {
        id: 7,
        category: 4,
        name: 'Paletas',
        description: 'Paletas de caramelo frutales',
        weight: '12 docenas',
        price: 15,
    },
    {
        id: 8,
        category: 4,
        name: 'Paletas acidas',
        description: 'paletas acida/dulce',
        weight: '12 docenas',
        price: 20,
    },
]